const STORAGE_KEY='fitWarehouseCareer_v3';

const ROLES=[
 {id:'outsourcer',name:'Аутсорс',goal:80,desc:'Собирай пустую тару и держи серию.'},
 {id:'seniorOutsourcer',name:'Старший аутсорс',goal:5,desc:'Распределяй людей по участкам и выполняй план смены.'},
 {id:'intake',name:'Приёмка',goal:8,desc:'Сверяй поставки, находи недостачи и брак.'},
 {id:'placement',name:'Размещение',goal:8,desc:'Выбирай правильные ячейки для товара.'},
 {id:'picker',name:'Сборщик заказов',goal:10,desc:'Собирай заказы по маршруту без ошибок.'},
 {id:'forklift',name:'Водитель ПРТ',goal:8,desc:'Вози паллеты по складу и не задевай стеллажи.'},
 {id:'logistician',name:'Логист',goal:10,desc:'Распределяй доставки между машинами.'},
 {id:'shiftLead',name:'Начальник смены',goal:8,desc:'Балансируй людей между зонами склада.'},
 {id:'warehouseLead',name:'Начальник склада',goal:10,desc:'Управляй бюджетом, техникой и KPI склада.'},
 {id:'operationsDirector',name:'Операционный директор',goal:12,desc:'Развивай сеть складов и удерживай прибыль.'},
 {id:'ceo',name:'Генеральный директор',goal:14,desc:'Принимай решения в кризисах и выполняй цели компании.'},
 {id:'owner',name:'Собственник FIT',goal:0,desc:'Компания твоя. Теперь ты строишь империю.'}
];

const defaults={started:false,name:'',roleIndex:0,money:0,todayEarned:0,reputation:0,careerPoints:0,progress:0,totalActions:0,combo:0,bestCombo:0,activeTab:'home',sound:true,quality:100,energy:100,workData:{}};
let state=load();
let timers=[];

function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return {...defaults}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));syncHeader()}
function q(id){return document.getElementById(id)}
function role(){return ROLES[state.roleIndex]||ROLES[0]}
function fmt(n){return Math.round(n).toLocaleString('ru-RU')+' ₽'}
function esc(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function pct(){return role().goal?Math.min(100,Math.round(state.progress/role().goal*100)):100}
function toast(t){const e=q('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1500)}
function stopTimers(){timers.forEach(clearInterval);timers.forEach(clearTimeout);timers=[]}
function syncHeader(){if(q('headerStatus'))q('headerStatus').textContent=state.started?role().name:'Первый рабочий день'}
function showNav(on){q('bottomNav')?.classList.toggle('hidden',!on)}
function setTab(tab){state.activeTab=tab;save();render()}
function reward(cash=0,rep=0,cp=0){state.money+=cash;state.todayEarned+=cash;state.reputation=Math.max(0,state.reputation+rep);state.careerPoints+=cp;state.totalActions++;save()}
function ensureData(key,factory){if(!state.workData)state.workData={};if(!state.workData[key])state.workData[key]=factory();return state.workData[key]}
function clearRoleData(){state.workData={};state.progress=0;state.combo=0;state.quality=100;state.energy=100}

function render(){stopTimers();syncHeader();if(!state.started){showNav(false);return onboarding()}showNav(true);document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.activeTab));if(state.activeTab==='work')return work();if(state.activeTab==='career')return career();if(state.activeTab==='profile')return profile();home()}

function onboarding(){q('screen').innerHTML=`<section class="hero"><div class="eyebrow">FIT / карьерный симулятор</div><h1>С нуля на складе — до собственника FIT.</h1><p>Каждая должность — отдельная игровая механика. Чем выше карьера, тем больше ответственности и сложнее повышение.</p><div class="card onboarding-card"><label class="small muted">Имя сотрудника</label><input id="nameInput" class="input" maxlength="18" placeholder="Введите имя"><button id="startBtn" class="primary">Устроиться в FIT</button></div></section><div class="stats"><div class="stat-card"><span>Старт</span><b>Аутсорс</b></div><div class="stat-card"><span>Финал</span><b>Собственник</b></div><div class="stat-card"><span>Должностей</span><b>${ROLES.length}</b></div><div class="stat-card"><span>Полный путь</span><b>≈ 2 недели</b></div></div>`;q('startBtn').onclick=()=>{const name=q('nameInput').value.trim();if(name.length<2)return toast('Введите имя');state={...defaults,started:true,name,activeTab:'home',workData:{}};save();render()}}

function home(){q('screen').innerHTML=`<section class="dashboard-head"><div><div class="eyebrow">Сотрудник FIT</div><h1>${esc(state.name)}</h1><p>${role().name}</p></div><div class="rank-pill">${state.roleIndex+1}/${ROLES.length}</div></section><div class="stats"><div class="stat-card"><span>Баланс</span><b>${fmt(state.money)}</b></div><div class="stat-card"><span>Сегодня</span><b>${fmt(state.todayEarned)}</b></div><div class="stat-card"><span>Репутация</span><b>${state.reputation}</b></div><div class="stat-card"><span>Карьерный рейтинг</span><b>${state.careerPoints}</b></div></div><section class="card focus-card"><div class="card-head"><div><div class="small muted">ТЕКУЩАЯ ДОЛЖНОСТЬ</div><h3>${role().name}</h3></div><span class="badge orange">${state.progress}/${role().goal||'∞'}</span></div><p class="muted small">${role().desc}</p><div class="progress"><i style="width:${pct()}%"></i></div><button id="goWork" class="primary">Начать смену</button></section><section class="card"><div class="card-head"><h3>Следующая ступень</h3><span class="badge">${state.roleIndex<ROLES.length-1?ROLES[state.roleIndex+1].name:'Финал'}</span></div><p class="muted small">Повышение выдаётся только после выполнения норматива текущей должности. Ошибки замедляют прогресс.</p></section>`;q('goWork').onclick=()=>setTab('work')}

function work(){switch(role().id){case'outsourcer':return outsourcer();case'seniorOutsourcer':return seniorOutsourcer();case'intake':return intake();case'placement':return placement();case'picker':return picker();case'forklift':return forklift();case'logistician':return logistician();case'shiftLead':return shiftLead();case'warehouseLead':return warehouseLead();case'operationsDirector':return operationsDirector();case'ceo':return ceo();default:return owner()}}

function workHeader(title,sub){return `<div class="eyebrow">Смена / ${role().name}</div><h2 class="section-title">${title}</h2><p class="section-subtitle">${sub}</p><section class="card compact"><div class="work-stats"><div><span>ПРОГРЕСС</span><b>${state.progress}/${role().goal||'∞'}</b></div><div><span>РЕПУТАЦИЯ</span><b>${state.reputation}</b></div><div><span>ЗАРАБОТАНО</span><b>${fmt(state.todayEarned)}</b></div></div><div class="progress"><i style="width:${pct()}%"></i></div></section>`}

function outsourcer(){q('screen').innerHTML=workHeader('Пустая тара','Нажимай на коробки до исчезновения. Серия без пропусков повышает оплату.')+`<div id="workZone" class="work-zone"><div class="warehouse-bg"><div class="rack r1"></div><div class="rack r2"></div><div class="rack r3"></div></div><div class="conveyor"></div><div class="shift-note">Коробка = деньги + рейтинг</div><div class="combo-badge" id="comboBadge">Комбо x${state.combo}</div></div>`;spawnBox();timers.push(setInterval(spawnBox,780))}
function spawnBox(){const zone=q('workZone');if(!zone||zone.querySelectorAll('.box').length>=5)return;const b=document.createElement('button');const rare=Math.random()<.12;b.className='box'+(rare?' rare':'');b.innerHTML=rare?'<span>FIT</span><small>+8</small>':'<span>FIT</span><small>+3</small>';b.style.left=(8+Math.random()*76)+'%';b.style.bottom=(72+Math.random()*95)+'px';let hit=false;b.onclick=()=>{if(hit)return;hit=true;state.progress++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);const gain=(rare?8:3)+Math.min(5,Math.floor(state.combo/5));reward(gain,rare?3:1,1+Math.floor(state.combo/6));b.classList.add('hit');q('comboBadge').textContent='Комбо x'+state.combo;if(state.progress>=role().goal)return setTimeout(promote,150);setTimeout(()=>b.remove(),100)};zone.appendChild(b);timers.push(setTimeout(()=>{if(!hit&&b.isConnected){state.combo=0;save();b.remove();if(q('comboBadge'))q('comboBadge').textContent='Комбо x0'}},2100))}

function seniorOutsourcer(){const d=ensureData('team',()=>({round:1,workers:makeWorkers(),assign:{}}));q('screen').innerHTML=workHeader('Управление бригадой','Распредели сотрудников туда, где их навыки дадут максимальный результат.')+`<section class="card"><div class="card-head"><h3>Смена ${state.progress+1} из ${role().goal}</h3><span class="badge orange">План ≥ 82%</span></div><div class="load-row"><span>Тара <b>${d.loads?.boxes||72}%</b></span><span>Сортировка <b>${d.loads?.sort||88}%</b></span><span>Подвоз <b>${d.loads?.move||64}%</b></span></div></section><div class="team-list">${d.workers.map(w=>`<div class="worker"><div class="worker-top"><div class="worker-name"><b>${w.name}</b><span>Скорость ${w.speed} · Точность ${w.accuracy} · Сила ${w.power}</span></div></div><div class="assign-grid">${['Тара','Сортировка','Подвоз'].map(a=>`<button class="assign ${d.assign[w.name]===a?'active':''}" data-worker="${w.name}" data-area="${a}">${a}</button>`).join('')}</div></div>`).join('')}</div><button id="teamCheck" class="primary">Запустить смену</button>`;document.querySelectorAll('.assign').forEach(b=>b.onclick=()=>{d.assign[b.dataset.worker]=b.dataset.area;save();seniorOutsourcer()});q('teamCheck').onclick=()=>{if(Object.keys(d.assign).length<d.workers.length)return toast('Распредели всех сотрудников');let score=0;d.workers.forEach(w=>{const a=d.assign[w.name];score+=a==='Тара'?w.speed:a==='Сортировка'?w.accuracy:w.power});score=Math.round(score/d.workers.length);if(score>=82){state.progress++;reward(160,6,12);toast('Смена выполнена: '+score+'%')}else{reward(40,-3,2);toast('План провален: '+score+'%')};state.workData.team={round:d.round+1,workers:makeWorkers(),assign:{},loads:randomLoads()};save();if(state.progress>=role().goal)setTimeout(promote,300);else seniorOutsourcer()}}
function makeWorkers(){const names=['Максим','Антон','Илья','Денис'];return names.map(n=>({name:n,speed:55+Math.floor(Math.random()*45),accuracy:55+Math.floor(Math.random()*45),power:55+Math.floor(Math.random()*45)}))}
function randomLoads(){return{boxes:60+Math.floor(Math.random()*35),sort:60+Math.floor(Math.random()*35),move:60+Math.floor(Math.random()*35)}}

function intake(){const d=ensureData('intake',makeIntake);q('screen').innerHTML=workHeader('Проверка поставки','Сверь накладную с фактом. Ошибка в приёмке снижает репутацию.')+`<section class="scenario"><div class="scenario-title">Поставка №${d.id}</div><div class="manifest"><b>${d.item}</b><br>По накладной: ${d.doc} шт.<br>Фактически на паллете: ${d.fact} шт.<br>Состояние: ${d.damage?'есть повреждение':'без повреждений'}</div><div class="choices">${d.options.map(x=>`<button class="choice" data-answer="${x.key}">${x.label}</button>`).join('')}</div></section>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer===d.correct;if(ok){state.progress++;reward(190,5,12);toast('Принято верно')}else{reward(30,-5,1);toast('Ошибка в приёмке')};state.workData.intake=makeIntake();save();if(state.progress>=role().goal)setTimeout(promote,300);else intake()})}
function makeIntake(){const items=['саморезы 4×50','кабель ВВГ','розетки','перчатки','сверла','крепёжные уголки'];const doc=10+Math.floor(Math.random()*40);const delta=[-2,-1,0,0,0,1][Math.floor(Math.random()*6)];const fact=doc+delta;const damage=Math.random()<.25;let correct=damage?'damage':delta===0?'accept':'diff';return{id:1000+Math.floor(Math.random()*9000),item:items[Math.floor(Math.random()*items.length)],doc,fact,damage,correct,options:[{key:'accept',label:'Принять без расхождений'},{key:'diff',label:'Оформить расхождение'},{key:'damage',label:'Отправить в зону брака'}]}}

function placement(){const d=ensureData('placement',makePlacement);q('screen').innerHTML=workHeader('Размещение товара','Выбери ячейку с учётом веса, оборачиваемости и типа товара.')+`<section class="scenario"><div class="scenario-title">${d.item}</div><div class="manifest">Вес: ${d.weight} кг<br>Оборачиваемость: ${d.turnover}<br>Тип: ${d.type}</div><div class="slot-grid">${d.slots.map(s=>`<button class="slot" data-slot="${s.id}"><b>${s.id}</b><span>${s.desc}</span></button>`).join('')}</div></section>`;document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{if(b.dataset.slot===d.correct){state.progress++;reward(210,5,13);toast('Размещено правильно')}else{reward(20,-4,1);toast('Неудачная ячейка')};state.workData.placement=makePlacement();save();if(state.progress>=role().goal)setTimeout(promote,300);else placement()})}
function makePlacement(){const heavy=Math.random()<.45,fast=Math.random()<.5;const item=heavy?'ящик крепежа':'электрика в коробах';const slots=[{id:'A-01-01',desc:'нижний ярус · близко к сборке'},{id:'A-04-03',desc:'верхний ярус · близко к сборке'},{id:'C-01-08',desc:'нижний ярус · далеко'},{id:'C-05-10',desc:'верхний ярус · далеко'}];let correct=heavy?(fast?'A-01-01':'C-01-08'):(fast?'A-04-03':'C-05-10');return{item,weight:heavy?420:36,turnover:fast?'высокая':'низкая',type:heavy?'тяжёлый товар':'лёгкий товар',slots,correct}}

function picker(){const d=ensureData('picker',makeOrder);q('screen').innerHTML=workHeader('Сборка заказа','Иди по ячейкам в правильной последовательности и бери точное количество.')+`<section class="card"><div class="card-head"><h3>Заказ ${d.order}</h3><span class="badge orange">Маршрут ${d.step+1}/${d.route.length}</span></div><div class="order-list">${d.route.map((x,i)=>`<div class="order-row ${i<d.step?'done':''} ${i===d.step?'current':''}"><b>${x.cell}</b><span>${x.qty} шт.</span></div>`).join('')}</div></section><section class="picker-controls"><p class="muted small">Следующая ячейка:</p><div class="choices">${shuffle([d.route[d.step].cell,'B-'+rand(1,12)+'-'+rand(1,9),'C-'+rand(1,12)+'-'+rand(1,9)]).map(c=>`<button class="choice" data-cell="${c}">${c}</button>`).join('')}</div></section>`;document.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{if(b.dataset.cell===d.route[d.step].cell){d.step++;reward(35,1,2);if(d.step>=d.route.length){state.progress++;reward(260,6,14);toast('Заказ собран');state.workData.picker=makeOrder()}else toast('Верно, дальше') }else{reward(0,-3,0);d.errors++;toast('Лишний проход — ошибка')};save();if(state.progress>=role().goal)setTimeout(promote,300);else picker()})}
function makeOrder(){return{order:'#'+rand(10000,99999),step:0,errors:0,route:Array.from({length:4},(_,i)=>({cell:String.fromCharCode(65+i)+'-'+String(rand(1,12)).padStart(2,'0')+'-'+String(rand(1,9)).padStart(2,'0'),qty:rand(1,6)}))}}

function forklift(){const d=ensureData('forklift',makeForklift);q('screen').innerHTML=workHeader('Погрузчик','Довези паллету до зелёной зоны. Стеллажи трогать нельзя.')+`<div class="forklift-board">${Array.from({length:25},(_,i)=>{const x=i%5,y=Math.floor(i/5),key=x+','+y,cls=key===d.player.join(',')?'truck':key===d.target.join(',')?'target':d.blocks.includes(key)?'block':'';return `<div class="cell ${cls}">${cls==='truck'?'ПРТ':cls==='target'?'ЦЕЛЬ':''}</div>`}).join('')}</div><div class="dpad"><button data-move="0,-1">↑</button><button data-move="-1,0">←</button><button data-move="1,0">→</button><button data-move="0,1">↓</button></div>`;document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const [dx,dy]=b.dataset.move.split(',').map(Number),nx=d.player[0]+dx,ny=d.player[1]+dy,key=nx+','+ny;if(nx<0||nx>4||ny<0||ny>4||d.blocks.includes(key)){reward(0,-2,0);toast('Удар о стеллаж');return}d.player=[nx,ny];reward(5,0,1);if(nx===d.target[0]&&ny===d.target[1]){state.progress++;reward(280,6,15);toast('Паллета доставлена');state.workData.forklift=makeForklift()};save();if(state.progress>=role().goal)setTimeout(promote,300);else forklift()})}
function makeForklift(){let blocks=['1,1','3,1','1,3','3,3'];return{player:[0,4],target:[4,0],blocks}}

function logistician(){const d=ensureData('logistician',makeLogistics);q('screen').innerHTML=workHeader('Планирование рейса','Выбери машину, которая увезёт груз вовремя и без перегруза.')+`<section class="scenario"><div class="scenario-title">Доставка ${d.city}</div><div class="manifest">Груз: ${d.weight} т<br>Паллет: ${d.pallets}<br>Дедлайн: ${d.deadline}</div><div class="fleet-list">${d.cars.map(c=>`<button class="fleet" data-car="${c.id}"><b>${c.name}</b><span>вместимость ${c.cap} т · свободна через ${c.wait} ч.</span></button>`).join('')}</div></section>`;document.querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>{const c=d.cars.find(x=>x.id===b.dataset.car),ok=c.cap>=d.weight&&c.wait<=d.maxWait;if(ok){state.progress++;reward(320,6,16);toast('Маршрут закрыт')}else{reward(20,-5,1);toast(c.cap<d.weight?'Перегруз':'Не успеет к дедлайну')};state.workData.logistician=makeLogistics();save();if(state.progress>=role().goal)setTimeout(promote,300);else logistician()})}
function makeLogistics(){const weight=rand(2,10),maxWait=rand(1,3);return{city:['Лобня','Химки','Долгопрудный','Мытищи'][rand(0,3)],weight,pallets:rand(3,14),deadline:(12+rand(1,7))+':00',maxWait,cars:[{id:'a',name:'Газель',cap:3,wait:0},{id:'b',name:'5-тонник',cap:5,wait:1},{id:'c',name:'10-тонник',cap:10,wait:2}]}}

function shiftLead(){const d=ensureData('shift',()=>({people:36,alloc:{pick:12,place:12,intake:12},load:{pick:rand(80,140),place:rand(70,125),intake:rand(65,120)}}));const zones=[['pick','Сборка'],['place','Размещение'],['intake','Приёмка']];q('screen').innerHTML=workHeader('Управление сменой','Распредели 36 человек так, чтобы перегруженные зоны получили больше людей.')+`<section class="card"><div class="zone-grid">${zones.map(([k,n])=>`<div class="zone"><div><b>${n}</b><span>Нагрузка ${d.load[k]}%</span></div><div class="counter"><button data-minus="${k}">−</button><strong>${d.alloc[k]}</strong><button data-plus="${k}">+</button></div></div>`).join('')}</div><button id="shiftRun" class="primary">Запустить смену</button></section>`;document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>adjustAlloc(d,b.dataset.plus,1));document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>adjustAlloc(d,b.dataset.minus,-1));q('shiftRun').onclick=()=>{const total=Object.values(d.alloc).reduce((a,b)=>a+b,0);if(total!==36)return toast('Распредели ровно 36 сотрудников');let score=0;Object.keys(d.alloc).forEach(k=>{const need=d.load[k]/100*12;score+=Math.max(0,100-Math.abs(d.alloc[k]-need)*8)});score=Math.round(score/3);if(score>=82){state.progress++;reward(450,8,22);toast('Смена закрыта: '+score+'%')}else{reward(40,-6,2);toast('Склад просел: '+score+'%')};state.workData.shift=null;save();if(state.progress>=role().goal)setTimeout(promote,300);else shiftLead()}}
function adjustAlloc(d,k,v){if(d.alloc[k]+v<2)return;d.alloc[k]+=v;save();shiftLead()}

function warehouseLead(){const d=ensureData('warehouse',()=>({budget:100,kpi:78,staff:74,equipment:68,event:makeWarehouseEvent()}));q('screen').innerHTML=workHeader('Управление складом','Трать ограниченный бюджет. Нужно удерживать эффективность выше 85%.')+`<div class="stats"><div class="stat-card"><span>Бюджет</span><b>${d.budget}</b></div><div class="stat-card"><span>KPI</span><b>${d.kpi}%</b></div><div class="stat-card"><span>Персонал</span><b>${d.staff}%</b></div><div class="stat-card"><span>Техника</span><b>${d.equipment}%</b></div></div><section class="scenario"><div class="scenario-title">${d.event.title}</div><p class="muted small">${d.event.text}</p><div class="choice-stack">${d.event.options.map((o,i)=>`<button class="choice wide" data-opt="${i}">${o.label}<small>Стоимость ${o.cost}</small></button>`).join('')}</div></section>`;document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{const o=d.event.options[Number(b.dataset.opt)];if(d.budget<o.cost)return toast('Не хватает бюджета');d.budget-=o.cost;d.kpi=Math.min(100,d.kpi+o.kpi);d.staff=Math.min(100,d.staff+o.staff);d.equipment=Math.min(100,d.equipment+o.equipment);if(d.kpi>=85){state.progress++;reward(550,8,25)}else reward(80,-3,4);d.budget=Math.min(100,d.budget+20);d.event=makeWarehouseEvent();save();toast('Решение принято');if(state.progress>=role().goal)setTimeout(promote,300);else warehouseLead()})}
function makeWarehouseEvent(){const events=[{title:'Сломался погрузчик',text:'Один ПРТ выбыл в час пик.',options:[{label:'Срочный ремонт',cost:35,kpi:10,staff:0,equipment:18},{label:'Перераспределить технику',cost:10,kpi:4,staff:-3,equipment:2}]},{title:'Не вышли сотрудники',text:'На смену не пришли 7 человек.',options:[{label:'Вызвать аутсорс',cost:30,kpi:9,staff:12,equipment:0},{label:'Усилить оставшихся',cost:10,kpi:3,staff:-8,equipment:0}]},{title:'Пик заказов',text:'Объём сборки вырос на 28%.',options:[{label:'Доп. смена',cost:28,kpi:12,staff:-2,equipment:-2},{label:'Перебросить людей',cost:8,kpi:5,staff:-4,equipment:0}]}];return events[rand(0,events.length-1)]}

function operationsDirector(){const d=ensureData('ops',()=>({cash:300,sites:[{n:'Москва',eff:91},{n:'Тула',eff:74},{n:'Тверь',eff:81}],round:1}));q('screen').innerHTML=workHeader('Сеть складов','Инвестируй туда, где это сильнее всего поднимет общую эффективность.')+`<section class="card"><div class="card-head"><h3>Инвестбюджет</h3><span class="badge orange">${d.cash} млн</span></div><div class="site-list">${d.sites.map((s,i)=>`<div class="site"><div><b>${s.n}</b><span>Эффективность ${s.eff}%</span></div><button data-invest="${i}">+10 млн</button></div>`).join('')}</div><button id="opsFinish" class="primary">Завершить квартал</button></section>`;document.querySelectorAll('[data-invest]').forEach(b=>b.onclick=()=>{if(d.cash<10)return toast('Бюджет закончился');d.cash-=10;d.sites[Number(b.dataset.invest)].eff=Math.min(100,d.sites[Number(b.dataset.invest)].eff+rand(2,5));save();operationsDirector()});q('opsFinish').onclick=()=>{const avg=Math.round(d.sites.reduce((a,s)=>a+s.eff,0)/d.sites.length);if(avg>=86){state.progress++;reward(800,10,35);toast('Квартал успешный: '+avg+'%')}else{reward(100,-6,3);toast('Сеть отстаёт: '+avg+'%')};state.workData.ops={cash:300,sites:d.sites.map(s=>({...s,eff:Math.max(65,s.eff-rand(2,6))})),round:d.round+1};save();if(state.progress>=role().goal)setTimeout(promote,300);else operationsDirector()}}

function ceo(){const d=ensureData('ceo',makeCeo);q('screen').innerHTML=workHeader('Совет директоров','У каждого решения есть последствия. Нужно провести компанию через серию кризисов.')+`<section class="scenario"><div class="scenario-title">${d.title}</div><p class="muted small">${d.text}</p><div class="ceo-kpis"><span>Прибыль <b>${d.profit}</b></span><span>Люди <b>${d.people}</b></span><span>Репутация <b>${d.brand}</b></span></div><div class="choice-stack">${d.options.map((o,i)=>`<button class="choice wide" data-ceo="${i}">${o.label}</button>`).join('')}</div></section>`;document.querySelectorAll('[data-ceo]').forEach(b=>b.onclick=()=>{const o=d.options[Number(b.dataset.ceo)];d.profit+=o.p;d.people+=o.h;d.brand+=o.b;const ok=d.profit>0&&d.people>0&&d.brand>0;if(ok){state.progress++;reward(1100,12,45)}else reward(100,-8,4);state.workData.ceo=makeCeo(d);save();toast(ok?'Решение принято':'Компания получила удар');if(state.progress>=role().goal)setTimeout(promote,300);else ceo()})}
function makeCeo(prev){const cases=[{title:'Крупный клиент требует скидку',text:'Если отказать — есть риск потерять контракт.',options:[{label:'Дать скидку',p:-8,h:1,b:8},{label:'Отказать',p:6,h:0,b:-9},{label:'Предложить SLA-пакет',p:2,h:-2,b:5}]},{title:'Нужно открыть новый склад',text:'Совет спорит между быстрым ростом и осторожностью.',options:[{label:'Открывать сейчас',p:-10,h:5,b:9},{label:'Подождать',p:4,h:0,b:-3},{label:'Арендовать временный',p:-4,h:1,b:5}]},{title:'Срыв доставки',text:'Партия заказов опаздывает на сутки.',options:[{label:'Компенсировать клиентам',p:-7,h:0,b:10},{label:'Ничего не делать',p:3,h:0,b:-12},{label:'Усилить ночную смену',p:-4,h:-5,b:7}]}];const c=cases[rand(0,cases.length-1)];return{...c,profit:prev?.profit??70,people:prev?.people??70,brand:prev?.brand??70}}

function owner(){q('screen').innerHTML=`<div class="eyebrow">Финал карьеры</div><h2 class="section-title">Собственник FIT</h2><section class="hero final-hero"><h1>Ты прошёл путь от пустых коробок до владельца компании.</h1><p>Карьерная кампания завершена. Следующий этап — режим бесконечного развития компании.</p></section><section class="card"><div class="kpi"><span>Баланс</span><b>${fmt(state.money)}</b></div><div class="kpi"><span>Репутация</span><b>${state.reputation}</b></div><div class="kpi"><span>Карьерный рейтинг</span><b>${state.careerPoints}</b></div></section>`}

function promote(){stopTimers();if(state.roleIndex>=ROLES.length-1)return;const next=ROLES[state.roleIndex+1];q('modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="eyebrow">Отдел кадров FIT</div><h2>Повышение получено</h2><p>Ты выполнил норматив должности <b>${role().name}</b>.</p><div class="promotion-box"><span>Новая должность</span><strong>${next.name}</strong></div><button id="acceptPromotion" class="primary">Принять должность</button></div></div>`;q('acceptPromotion').onclick=()=>{state.roleIndex++;clearRoleData();state.reputation+=10+state.roleIndex*2;state.careerPoints+=30+state.roleIndex*12;state.activeTab='home';save();q('modalRoot').innerHTML='';render();toast('Новая должность: '+role().name)}}

function career(){q('screen').innerHTML=`<div class="eyebrow">Карьерная карта</div><h2 class="section-title">Путь в FIT</h2><p class="section-subtitle">Каждый следующий этап сложнее предыдущего.</p><div class="career-list">${ROLES.map((r,i)=>`<div class="career-node ${i===state.roleIndex?'current':''} ${i>state.roleIndex?'locked':''}"><div class="career-step">${String(i+1).padStart(2,'0')}</div><div><strong>${r.name}</strong><span>${i<state.roleIndex?'Пройдено':i===state.roleIndex?r.desc:'Закрыто'}</span></div><div class="career-state">${i<state.roleIndex?'✓':i===state.roleIndex?pct()+'%':'—'}</div></div>`).join('')}</div>`}
function profile(){q('screen').innerHTML=`<div class="eyebrow">Личное дело</div><h2 class="section-title">${esc(state.name)}</h2><section class="card profile-card"><div class="kpi"><span>Должность</span><b>${role().name}</b></div><div class="kpi"><span>Баланс</span><b>${fmt(state.money)}</b></div><div class="kpi"><span>Репутация</span><b>${state.reputation}</b></div><div class="kpi"><span>Карьерный рейтинг</span><b>${state.careerPoints}</b></div><div class="kpi"><span>Лучшее комбо</span><b>x${state.bestCombo}</b></div><div class="kpi"><span>Всего действий</span><b>${state.totalActions}</b></div></section><button id="resetBtn" class="secondary">Начать карьеру заново</button>`;q('resetBtn').onclick=()=>{if(confirm('Сбросить весь прогресс?')){localStorage.removeItem(STORAGE_KEY);state={...defaults,workData:{}};render()}}}
function rand(a,b){return a+Math.floor(Math.random()*(b-a+1))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}

document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
q('soundToggle')?.addEventListener('click',()=>{state.sound=!state.sound;save();toast(state.sound?'Звук включён':'Звук выключен')});
render();